version: '3'

volumes:
  postsql_vol:

networks:
  produto_net:
    driver: bridge

services:
  postsql:
    image: postgres:14.5
    ports:
      - 5432:5432
    networks:
      - produto_net
    volumes:
      - postsql_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpwd
  pgadmin:
    image: dpage/pgadmin4:6.15
    ports:
      - 8080:80
    networks:
      - produto_net
    depends_on:
      - postsql
    environment:
      - PGADMIN_DEFAULT_EMAIL=postuser@postuser.com
      - PGADMIN_DEFAULT_PASSWORD=postpwd

